# Fail on warnings - also for files referenced in subdirs
# -Werror can be disabled for specific files using:
# CFLAGS_<file.o> := -Wno-error
ifndef CONFIG_KVM_MIPS_LOONGSON3
ifndef CONFIG_LOONGSON_GUEST_OS
subdir-ccflags-y := -Werror
endif
endif

# platform specific definitions
include arch/mips/Kbuild.platforms
obj-y := $(platform-y)

# make clean traverses $(obj-) without having included .config, so
# everything ends up here
obj- := $(platform-)

# mips object files
# The object files are linked as core-y files would be linked

obj-y += kernel/
obj-y += mm/
obj-y += math-emu/

ifdef CONFIG_KVM
obj-y += kvm/
endif
