#
# Common code for all Loongson3 based systems
#

obj-$(CONFIG_MACH_LOONGSON3) += common/

#
# Loongson3 board with rs780 north bridge
#

obj-$(CONFIG_LOONGSON_MACH3X) += rs780/

#
# Loongson3 board with ls2h south bridge
#

obj-$(CONFIG_LS2H_SB) += ls2h/
